version: '3.1'

services:
  fast-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
      #args:
       # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
       # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
       # - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
       # - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    container_name: fast-api
    ports:
      - 8000:8000
   # environment:
      #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      #- AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      #- FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    # bridge - connect to docker container from localhost
    network_mode: bridge